[package]
name = "core"
version = "0.1.1"
edition = "2021"
authors = ["Open Canarias S.L.<taple@opencanarias.com>"]
description = "TAPLE Protocol reference implementation"
# Remove when crates.io is published
documentation = "https://www.taple.es" 
readme = "../README.md"
homepage = "https://www.taple.es"
repository = "https://github.com/opencanarias/taple-core"
license = "AGPL-3.0-only"
keywords = ["blockchain", "distributed-ledger", "taple", "sustainability"]

[dependencies]
tokio = { workspace = true, features = [
	"default",
	"time",
	"rt",
	"rt-multi-thread",
	"sync",
	"macros",
] }
config = { workspace = true, features = ["toml"] }
serde = { workspace = true }
serde_json = { workspace = true }
tempdir = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
hex = { workspace = true }

chrono = { workspace = true, features = ["clock"] }

# API
commons = { path = "../commons" }
message = { path = "../message" }
network = { path = "../network" }
protocol = { path = "../protocol" }
governance = { path = "../governance" }
ledger = { path = "../ledger" }
thiserror = { workspace = true }
utoipa = { workspace = true }

[dependencies.libp2p]
workspace = true
features = ["identify", "kad", "mplex", "noise", "ping", "serde", "tcp-tokio"]

[dev-dependencies]
serial_test = "1.0.0"