[package]
name = "taple-core"
version = "0.2.0-dev"
edition = "2021"
authors = ["Open Canarias S.L.<taple@opencanarias.com>"]
description = "TAPLE Protocol reference implementation"
# Remove when crates.io is published
documentation = "https://www.taple.es"
readme = "../README.md"
homepage = "https://www.taple.es"
repository = "https://github.com/opencanarias/taple-core"
license = "AGPL-3.0-only"
keywords = ["blockchain", "distributed-ledger", "taple", "sustainability"]

[features]
default = [ "mobile" ]
# default = ["secp256k1", "x25519", "sha2", "sha3", "blake2", "evaluation"]
evaluation = [ "dep:wasmtime", "dep:wasm-gc-api" ]
mobile = ["secp256k1", "x25519", "sha2", "sha3", "blake2"]
secp256k1 = ["libsecp256k1"]
x25519 = ["x25519-dalek", "curve25519-dalek"]

[dependencies]
tokio = { version = "~1.20", features = [
	"default",
	"time",
	"rt",
	"rt-multi-thread",
	"sync",
	"macros",
] }
config = { version = "~0.13.2", features = ["toml"] }
serde = { version = "~1.0", features = ["derive"] }
serde_json = { version = "~1.0" }
async-trait = { version = "~0.1.56" }
futures = { version = "~0.3.24" }
env_logger = { version = "^0.10" }
log = { version = "~0.4" }
hex = { version = "~0.4.3" }
jsonschema = { version = "~0.16" }
time = { version = "^0.3", features = ["std"] }

# API
thiserror = { version = "~1.0" }
utoipa = { version = "~2" }

# Protocol
tokio-stream = { version = "~0.1" }
rmp-serde = { version = "~1" }
borsh = { version = "~0.9.3" }
blake3 = { version = "~1.0" }
rand = { version = "~0.8.5", features = ["small_rng"] }

# Network
instant = { version = "~0.1.11" }
unsigned-varint = { version = "~0.7", features = ["futures"] }
async-std = { version = "~1.12.0", features = ["attributes"] }
bincode = { version = "~1.3" }

# Message
serde_cbor = { version = "~0.11.2" }
dashmap = { version = "~5.4.0" }

# Ledger
base64 = { version = "~0.13" }

# Commons
getrandom = { version = "~0.2" }
json-patch = { version = "~0.2" }
rand_core = { version = "~0.5" }
ed25519-dalek = { version = "^1", features = ["serde"] }
libsecp256k1 = { version = "~0.7", optional = true }
x25519-dalek = { version = "~1.1.0", optional = true }
curve25519-dalek = { version = "~3.0.0", optional = true }
blake2 = { version = "~0.9", optional = true }
sha2 = { version = "~0.10", optional = true }
sha3 = { version = "~0.10", optional = true }

## Evaluator
wasmtime = { version = "^5.0.0", features = ["cache"], optional = true }
wasm-gc-api = { version = "~0.1.11", optional = true }

db-key = { version = "^0.0.5" }  #Usar esta versión. Necesario para implementar custom keys para leveldb::Database
url = { version = "~2.3.1" }

[dependencies.libp2p]
version = "~0.45"
features = [
	"identify",
	"kad",
	"mplex",
	"noise",
	"serde",
	"tcp-tokio",
	"yamux",
	"dns-tokio",
	"request-response"
]
default-features = false

[dev-dependencies]
serial_test = "1.0.0"
leveldb = "^0.8"
bs58 = "^0.4.0"
rand = "^0.8.5"
